#cloud-config

package_upgrade: true

users:
  - name: David
    gecos: David
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD2GXFhyfUjXqAlgWLRYI8UQbKfz5fpoy4oKW7ZYEqdMvvca/JyThyyZATz0SD0fgxKzD+Vc8ecCM6JEfKT2xZJVgVL7O50TGqUpzLWLJtItUcrskUsOrhLRGsAJuNOV2OeNeHGdYeMOKflBQ4YEUqjRnmQwA/Sz7/kzcc9fTzsu2YHv9UqYy1z+92kIg4XNDUXxr5O+w5bZTaYG0eyiOJr1gTkGVtrRjsoAmUivoCmz08mWIqvXPSNPRGBOuGtlC+Izzx0Qo+2Duyp5Mjf5EA5lItRo2GzfgDp6qVPEoG2ZfuNLk2Hw6PqkzPifOQwYQ0IeJyr0P2WRmmwqii4k/Hd dthowes@umich.edu

EOF
